/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/pages-json

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/me/me";
}

interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
